// KRUSHI-SOOTRA (कृषी-सूत्र)
// Branding, Localization, and Stakeholder Definitions

export const APP_NAME = 'KRUSHI-SOOTRA';
export const APP_NAME_DEVANAGARI = 'कृषी-सूत्र';
export const APP_TAGLINE = 'शेतीसाठी लागणारी प्रत्येक गोष्ट, एका ठिकाणी.';

export const ROLES = {
  FARMER: {
    id: 'farmer',
    name: 'Farmer',
    marathi: 'शेतकरी',
    hindi: 'किसान',
    icon: 'leaf',
    description: 'अवजारे, मजूर व साठवणूक सेवा शोधा',
  },
  EQUIPMENT_OWNER: {
    id: 'equipment_owner',
    name: 'Equipment Owner',
    marathi: 'अवजार मालक',
    hindi: 'उपकरण मालिक',
    icon: 'tractor',
    description: 'ट्रॅक्टर व अवजारे भाड्याने देऊन कमवा',
  },
  FARM_LABOUR: {
    id: 'farm_labour',
    name: 'Farm Labour',
    marathi: 'शेतमजूर',
    hindi: 'खेत मजदूर',
    icon: 'people',
    description: 'कामाच्या संधी व रोजंदारी मिळवा',
  },
  LABOUR_MUKADAM: {
    id: 'labour_mukadam',
    name: 'Labour Mukadam',
    marathi: 'मजूर मुकादम',
    hindi: 'मजदूर मुकादम',
    icon: 'briefcase',
    description: 'मजूर टोळी व्यवस्थापन व गट कामे',
  },
  WAREHOUSE_OWNER: {
    id: 'warehouse_owner',
    name: 'Warehouse Owner',
    marathi: 'गोदाम / शीतगृह मालक',
    hindi: 'गोदाम / कोल्ड स्टोरेज',
    icon: 'business',
    description: 'धान्य व भाजीपाला साठवणूक जागा भाड्याने द्या',
  },
};

export const CORE_MODULES = [
  {
    id: 'equipment',
    titleMr: 'कृषी अवजारे',
    titleEn: 'Equipment Rental',
    subtitleMr: 'ट्रॅक्टर, रोटाव्हेटर, हार्वेस्टर',
    icon: 'construct',
    color: '#1B5E20',
    badge: '२० किमी परिसर',
  },
  {
    id: 'labour',
    titleMr: 'शेतमजूर व टोळी',
    titleEn: 'Farm Labour & Teams',
    subtitleMr: 'खुरपणी, कापणी, फवारणी मजूर',
    icon: 'people',
    color: '#2E7D32',
    badge: 'सत्यापित मजूर',
  },
  {
    id: 'warehouse',
    titleMr: 'गोदाम व शीतगृह',
    titleEn: 'Warehouse & Cold Storage',
    subtitleMr: 'सुरक्षित साठवणूक व हमीभाव प्रतीक्षा',
    icon: 'home',
    color: '#0D47A1',
    badge: 'CCTV सुरक्षित',
  },
  {
    id: 'soil',
    titleMr: 'माती आरोग्य कार्ड OCR',
    titleEn: 'Soil Health Card OCR',
    subtitleMr: 'फोटो काढा आणि N-P-K विश्लेषण मिळवा',
    icon: 'document-text',
    color: '#B45309',
    badge: 'झटपट स्कॅन',
  },
  {
    id: 'disease',
    titleMr: 'पीक रोग व कीड निदान',
    titleEn: 'Crop Disease Diagnostics',
    subtitleMr: 'पानाचा फोटो काढून अचूक उपाय जाणून घ्या',
    icon: 'shield-checkmark',
    color: '#C2410C',
    badge: 'AI निदान',
  },
  {
    id: 'ai_assistant',
    titleMr: 'AI कृषी सल्लागार',
    titleEn: 'AI Krushi Assistant',
    subtitleMr: 'कोणताही शेती प्रश्न विचारा',
    icon: 'chatbubble-ellipses',
    color: '#7C3AED',
    badge: '२४/७ उपलब्ध',
  }
];

export const STRINGS = {
  mr: {
    welcome: 'नमस्कार',
    greetingSub: 'आज शेताचे नियोजन सोपे करूया',
    activeLocation: 'पुणे, महाराष्ट्र',
    changeLocation: 'बदला',
    weatherTitle: 'आजचे हवामान व शेती सल्ला',
    temp: 'तापमान',
    rainProb: 'पाऊस शक्यता',
    wind: 'वार्याचा वेग',
    humidity: 'आर्द्रता',
    nearbyServices: 'तुमच्या जवळ उपलब्ध सेवा',
    viewAll: 'सर्व पहा',
    bookNow: 'आता बुक करा',
    callNow: 'थेट संपर्क',
    distance: 'अंतरावर',
    perAcre: 'प्रति एकर',
    perDay: 'प्रति दिवस',
    perTonMonth: 'प्रति टन/महिना',
    verified: 'सत्यापित',
    roleSwitch: 'भूमिका बदला',
    currentRole: 'सध्याची भूमिका',
  },
  en: {
    welcome: 'Namaskar',
    greetingSub: "Let's organize your farm operations today",
    activeLocation: 'Pune, Maharashtra',
    changeLocation: 'Change',
    weatherTitle: 'Live Weather & Farm Advisory',
    temp: 'Temperature',
    rainProb: 'Rain Probability',
    wind: 'Wind Speed',
    humidity: 'Humidity',
    nearbyServices: 'Available Services Near You',
    viewAll: 'View All',
    bookNow: 'Book Now',
    callNow: 'Contact Provider',
    distance: 'away',
    perAcre: 'per acre',
    perDay: 'per day',
    perTonMonth: 'per ton/month',
    verified: 'Verified',
    roleSwitch: 'Switch Role',
    currentRole: 'Current Role',
  },
  hi: {
    welcome: 'नमस्कार',
    greetingSub: 'आज खेती का नियोजन आसान बनाएं',
    activeLocation: 'पुणे, महाराष्ट्र',
    changeLocation: 'बदलें',
    weatherTitle: 'आज का मौसम और कृषि सलाह',
    temp: 'तापमान',
    rainProb: 'बारिश की संभावना',
    wind: 'हवा की गति',
    humidity: 'आर्द्रता',
    nearbyServices: 'आपके निकट उपलब्ध सेवाएं',
    viewAll: 'सभी देखें',
    bookNow: 'अभी बुक करें',
    callNow: 'सीधा संपर्क',
    distance: 'दूरी',
    perAcre: 'प्रति एकड़',
    perDay: 'प्रति दिन',
    perTonMonth: 'प्रति टन/माह',
    verified: 'सत्यापित',
    roleSwitch: 'भूमिका बदलें',
    currentRole: 'वर्तमान भूमिका',
  }
};
