// KRUSHI-SOOTRA (कृषी-सूत्र / कृषि-सूत्र)
// Central Pure Localization & Multilingual Dictionary (100% Isolated Strings)
// Guarantees: When English is selected -> 0% Marathi/Hindi.
//             When Marathi is selected -> 0% English/Hindi.
//             When Hindi is selected   -> 0% English/Marathi.

export const BRANDING = {
  mr: {
    appName: 'कृषी-सूत्र',
    tagline: 'अद्ययावत शेती तंत्रज्ञान व थेट सेवा मंच',
    welcomeUser: 'सुस्वागतम',
    userStatus: 'सत्यापित कृषी उत्पादक',
    footerSub: 'शेतकरी, अवजार मालक व मजुरांचे एकात्मिक डिजिटल व्यासपीठ',
    copyright: 'सर्व हक्क सुरक्षित • शासन मान्यताप्राप्त कृषी मानके',
  },
  hi: {
    appName: 'कृषि-सूत्र',
    tagline: 'उन्नत कृषि तकनीक एवं सीधी सेवा मंच',
    welcomeUser: 'सुस्वागतम',
    userStatus: 'सत्यापित कृषि उत्पादक',
    footerSub: 'किसान, उपकरण मालिक और श्रमिकों का एकीकृत डिजिटल मंच',
    copyright: 'सर्वाधिकार सुरक्षित • शासन मान्यता प्राप्त कृषि मानक',
  },
  en: {
    appName: 'KRUSHI-SOOTRA',
    tagline: 'Next-Gen Precision Agri & Machinery Hub',
    welcomeUser: 'Welcome Back',
    userStatus: 'Verified Agri Producer',
    footerSub: 'Integrated digital platform for farmers, equipment owners & labour',
    copyright: 'All rights reserved • Certified Agricultural Standards',
  },
};

export const NAV_TABS = {
  mr: [
    { id: 'home', label: 'मुख्य', icon: 'home', outlineIcon: 'home-outline' },
    { id: 'equipment', label: 'अवजारे', icon: 'construct', outlineIcon: 'construct-outline' },
    { id: 'labour', label: 'मजूर', icon: 'people', outlineIcon: 'people-outline' },
    { id: 'storage', label: 'गोदाम', icon: 'business', outlineIcon: 'business-outline' },
    { id: 'lab', label: 'लॅब व AI', icon: 'flask', outlineIcon: 'flask-outline', badge: 'AI' },
    { id: 'profile', label: 'खाते', icon: 'person', outlineIcon: 'person-outline' },
  ],
  hi: [
    { id: 'home', label: 'मुख्य', icon: 'home', outlineIcon: 'home-outline' },
    { id: 'equipment', label: 'उपकरण', icon: 'construct', outlineIcon: 'construct-outline' },
    { id: 'labour', label: 'मजदूर', icon: 'people', outlineIcon: 'people-outline' },
    { id: 'storage', label: 'गोदाम', icon: 'business', outlineIcon: 'business-outline' },
    { id: 'lab', label: 'लैब और AI', icon: 'flask', outlineIcon: 'flask-outline', badge: 'AI' },
    { id: 'profile', label: 'प्रोफाइल', icon: 'person', outlineIcon: 'person-outline' },
  ],
  en: [
    { id: 'home', label: 'Home', icon: 'home', outlineIcon: 'home-outline' },
    { id: 'equipment', label: 'Equipment', icon: 'construct', outlineIcon: 'construct-outline' },
    { id: 'labour', label: 'Labour', icon: 'people', outlineIcon: 'people-outline' },
    { id: 'storage', label: 'Storage', icon: 'business', outlineIcon: 'business-outline' },
    { id: 'lab', label: 'Lab & AI', icon: 'flask', outlineIcon: 'flask-outline', badge: 'AI' },
    { id: 'profile', label: 'Profile', icon: 'person', outlineIcon: 'person-outline' },
  ],
};

export const CORE_MODULES_DATA = [
  {
    id: 'equipment',
    icon: 'construct',
    color: '#1B5E20',
    title: { mr: 'कृषी अवजारे', hi: 'कृषि उपकरण', en: 'Farm Equipment' },
    subtitle: { mr: 'ट्रॅक्टर, रोटाव्हेटर, हार्वेस्टर भाड्याने', hi: 'ट्रैक्टर, रोटावेटर, हार्वेस्टर किराये पर', en: 'Tractors, Rotavators, Harvesters on Rent' },
    badge: { mr: '२० किमी परिसर', hi: '२० किमी दायरा', en: 'Within 20 km' },
  },
  {
    id: 'labour',
    icon: 'people',
    color: '#2E7D32',
    title: { mr: 'शेतमजूर व टोळी', hi: 'खेत मजदूर और टोली', en: 'Farm Labour & Teams' },
    subtitle: { mr: 'खुरपणी, कापणी, फवारणी कुशल मजूर', hi: 'निराई, कटाई, छिड़काव कुशल श्रमिक', en: 'Weeding, Harvesting, Spraying Workers' },
    badge: { mr: 'सत्यापित मजूर', hi: 'सत्यापित श्रमिक', en: 'Verified Workers' },
  },
  {
    id: 'warehouse',
    icon: 'business',
    color: '#0D47A1',
    title: { mr: 'गोदाम व शीतगृह', hi: 'गोदाम और कोल्ड स्टोरेज', en: 'Warehouse & Cold Storage' },
    subtitle: { mr: 'धान्य व भाजीपाला सुरक्षित साठवणूक', hi: 'अनाज और सब्जी सुरक्षित भंडारण', en: 'Safe Grain & Vegetable Crop Storage' },
    badge: { mr: 'CCTV सुरक्षित', hi: 'CCTV सुरक्षित', en: 'CCTV Secured' },
  },
  {
    id: 'soil',
    icon: 'document-text',
    color: '#B45309',
    title: { mr: 'माती आरोग्य पत्रिका', hi: 'मृदा स्वास्थ्य कार्ड', en: 'Soil Health Card OCR' },
    subtitle: { mr: 'फोटो काढा आणि N-P-K विश्लेषण मिळवा', hi: 'फोटो लें और N-P-K विश्लेषण प्राप्त करें', en: 'Scan and extract N-P-K nutrient values' },
    badge: { mr: 'झटपट स्कॅन', hi: 'तुरंत स्कैन', en: 'Instant Scan' },
  },
  {
    id: 'disease',
    icon: 'shield-checkmark',
    color: '#C2410C',
    title: { mr: 'पीक रोग व कीड निदान', hi: 'फसल रोग और कीट निदान', en: 'Crop Disease Diagnosis' },
    subtitle: { mr: 'पानाचा फोटो काढून अचूक उपाय जाणून घ्या', hi: 'पत्ती का फोटो लेकर सटीक उपाय जानें', en: 'Photo scan of affected leaf with remedies' },
    badge: { mr: 'AI निदान', hi: 'AI निदान', en: 'AI Diagnostic' },
  },
  {
    id: 'ai_assistant',
    icon: 'chatbubble-ellipses',
    color: '#7C3AED',
    title: { mr: 'AI कृषी सल्लागार', hi: 'AI कृषि सलाहकार', en: 'AI Krushi Assistant' },
    subtitle: { mr: 'कोणताही शेती प्रश्न विचारा', hi: 'खेती से जुड़ा कोई भी प्रश्न पूछें', en: 'Instant expert answers for any farm query' },
    badge: { mr: '२४/७ तत्पर', hi: '२४/७ उपलब्ध', en: '24/7 Available' },
  },
];

export const ROLES_DATA = {
  farmer: {
    id: 'farmer',
    name: { mr: 'शेतकरी', hi: 'किसान', en: 'Farmer' },
    desc: { mr: 'अवजारे, मजूर व साठवणूक सेवा शोधा', hi: 'उपकरण, मजदूर और भंडारण सेवाएं खोजें', en: 'Discover equipment, labour & storage services' },
    icon: 'leaf',
  },
  equipment_owner: {
    id: 'equipment_owner',
    name: { mr: 'अवजार मालक', hi: 'उपकरण मालिक', en: 'Equipment Owner' },
    desc: { mr: 'ट्रॅक्टर व अवजारे भाड्याने देऊन कमवा', hi: 'ट्रैक्टर और उपकरण किराये पर देकर कमाएं', en: 'Rent out tractors & machinery to earn' },
    icon: 'construct',
  },
  farm_labour: {
    id: 'farm_labour',
    name: { mr: 'शेतमजूर', hi: 'खेत मजदूर', en: 'Farm Labour' },
    desc: { mr: 'शेती कामाच्या संधी व रोजंदारी मिळवा', hi: 'खेती के काम के अवसर और दैनिक मजदूरी पाएं', en: 'Find daily agricultural work opportunities' },
    icon: 'people',
  },
  labour_mukadam: {
    id: 'labour_mukadam',
    name: { mr: 'मजूर मुकादम', hi: 'मजदूर मुकादम', en: 'Labour Team Leader' },
    desc: { mr: 'मजूर टोळी व्यवस्थापन व गट कामे घ्या', hi: 'मजदूर टोली प्रबंधन और समूह कार्य लें', en: 'Manage worker teams & contract group jobs' },
    icon: 'briefcase',
  },
  warehouse_owner: {
    id: 'warehouse_owner',
    name: { mr: 'गोदाम / शीतगृह मालक', hi: 'गोदाम / कोल्ड स्टोरेज मालिक', en: 'Storage Facility Owner' },
    desc: { mr: 'धान्य व भाजीपाला साठवणूक जागा भाड्याने द्या', hi: 'अनाज और सब्जी भंडारण स्थान किराये पर दें', en: 'Lease out dry warehouse & cold storage space' },
    icon: 'business',
  },
};

export const UI_STRINGS = {
  mr: {
    welcome: 'नमस्कार',
    greetingSub: 'आज शेताचे नियोजन सोपे करूया',
    changeLocation: 'बदला',
    weatherTitle: 'आजचे हवामान व शेती सल्ला',
    temp: 'तापमान',
    rain: 'पाऊस',
    wind: 'वारा',
    humidity: 'आर्द्रता',
    feelsLike: 'जाणवणारे तापमान',
    nearbyServices: 'तुमच्या जवळ उपलब्ध सेवा',
    viewAll: 'सर्व पहा',
    bookNow: 'बुक करा',
    callNow: 'थेट संपर्क',
    distanceAway: 'अंतरावर',
    ratePerDay: '/दिवस',
    ratePerAcre: '/एकर',
    ratePerWorkerDay: '/मजूर/दिवस',
    ratePerTonMonth: '/टन/महिना',
    available: 'उपलब्ध',
    inUse: 'व्यस्त',
    verified: 'सत्यापित',
    coreServicesTitle: 'कृषी सेवा केंद्र',
    coreServicesSub: 'एकाच छताखाली शेतीची सर्व साधने',
    soilBannerTitle: 'माती आरोग्य पत्रिका स्कॅन करा',
    soilBannerDesc: 'नत्र, स्फुरद, पालाश व सामूचे कॅमेऱ्याने अचूक वाचन',
    scanAction: 'स्कॅन करा',
    aiBannerTitle: 'AI कृषी सल्लागार',
    aiBannerSub: 'शेतीतील कोणताही प्रश्न विचारा, तत्काळ मार्गदर्शन मिळवा',
    all: 'सर्व',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    myBookings: 'माझे बुकिंग ट्रॅकर',
    noBookings: 'अद्याप कोणतेही बुकिंग नाही',
    noBookingsSub: 'साधने आरक्षित केल्यावर येथे दिसतील',
    switchRole: 'तुमची भूमिका बदला',
    switchRoleSub: 'एकाच ॲपमधून शेतकरी किंवा सेवा पुरवठादार म्हणून काम करा',
    selectLanguage: 'भाषा निवडा',
    helplineTitle: 'किसान कॉल सेंटर',
    helplineNumber: '१८००-१८०-१५५१ (टोल-फ्री २४ तास)',
    helplineSub: 'शासकीय कृषी तज्ज्ञांशी मोफत थेट संवाद साधा',
    bookingSuccess: 'बुकिंग यशस्वी!',
    bookingConfirmed: 'बुकिंग निश्चित करा',
    totalAmount: 'एकूण देय रक्कम',
    daysCount: 'दिवसांची संख्या',
    acresCount: 'एकर संख्या',
    workersCount: 'मजुरांची संख्या',
    monthsCount: 'महिने',
    capacityTons: 'क्षमता',
    availableTons: 'मोकळी जागा',
    searchPlaceholder: 'शोधा...',
    offline: 'ऑफलाईन',
  },
  hi: {
    welcome: 'नमस्कार',
    greetingSub: 'आज खेती का नियोजन आसान बनाएं',
    changeLocation: 'बदलें',
    weatherTitle: 'आज का मौसम और कृषि सलाह',
    temp: 'तापमान',
    rain: 'बारिश',
    wind: 'हवा',
    humidity: 'आर्द्रता',
    feelsLike: 'महसूस होने वाला तापमान',
    nearbyServices: 'आपके निकट उपलब्ध सेवाएं',
    viewAll: 'सभी देखें',
    bookNow: 'बुक करें',
    callNow: 'सीधा संपर्क',
    distanceAway: 'दूरी पर',
    ratePerDay: '/दिन',
    ratePerAcre: '/एकड़',
    ratePerWorkerDay: '/श्रमिक/दिन',
    ratePerTonMonth: '/टन/माह',
    available: 'उपलब्ध',
    inUse: 'व्यस्त',
    verified: 'सत्यापित',
    coreServicesTitle: 'कृषि सेवा केंद्र',
    coreServicesSub: 'एक ही छत के नीचे खेती के सभी साधन',
    soilBannerTitle: 'मृदा स्वास्थ्य कार्ड स्कैन करें',
    soilBannerDesc: 'नाइट्रोजन, फास्फोरस, पोटाश और पीएच की कैमरे से सटीक रीडिंग',
    scanAction: 'स्कैन करें',
    aiBannerTitle: 'AI कृषि सलाहकार',
    aiBannerSub: 'खेती का कोई भी प्रश्न पूछें, तुरंत मार्गदर्शन प्राप्त करें',
    all: 'सभी',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    myBookings: 'मेरा बुकिंग ट्रैकर',
    noBookings: 'अभी कोई बुकिंग नहीं है',
    noBookingsSub: 'सुविधाएं आरक्षित करने पर यहां दिखाई देंगी',
    switchRole: 'अपनी भूमिका बदलें',
    switchRoleSub: 'एक ही ऐप से किसान या सेवा प्रदाता के रूप में कार्य करें',
    selectLanguage: 'भाषा चुनें',
    helplineTitle: 'किसान कॉल सेंटर',
    helplineNumber: '१८००-१८०-१५५१ (टोल-फ्री २४ घंटे)',
    helplineSub: 'सरकारी कृषि विशेषज्ञों से मुफ्त सीधी बातचीत करें',
    bookingSuccess: 'बुकिंग सफल!',
    bookingConfirmed: 'बुकिंग पक्की करें',
    totalAmount: 'कुल देय राशि',
    daysCount: 'दिनों की संख्या',
    acresCount: 'एकड़ संख्या',
    workersCount: 'श्रमिकों की संख्या',
    monthsCount: 'महीने',
    capacityTons: 'क्षमता',
    availableTons: 'रिक्त स्थान',
    searchPlaceholder: 'खोजें...',
    offline: 'ऑफलाइन',
  },
  en: {
    welcome: 'Welcome',
    greetingSub: "Let's organize your farm operations today",
    changeLocation: 'Change',
    weatherTitle: 'Live Weather & Farm Advisory',
    temp: 'Temperature',
    rain: 'Rain',
    wind: 'Wind',
    humidity: 'Humidity',
    feelsLike: 'Feels like',
    nearbyServices: 'Services Available Near You',
    viewAll: 'View All',
    bookNow: 'Book Now',
    callNow: 'Call Provider',
    distanceAway: 'away',
    ratePerDay: '/day',
    ratePerAcre: '/acre',
    ratePerWorkerDay: '/worker/day',
    ratePerTonMonth: '/ton/month',
    available: 'Available',
    inUse: 'In Use',
    verified: 'Verified',
    coreServicesTitle: 'Agricultural Services Hub',
    coreServicesSub: 'All farming operations under one single roof',
    soilBannerTitle: 'Scan Soil Health Card',
    soilBannerDesc: 'Instant camera OCR reading of Nitrogen, Phosphorus, Potassium & pH',
    scanAction: 'Scan Now',
    aiBannerTitle: 'AI Krushi Assistant',
    aiBannerSub: 'Ask any agronomy question for instant expert guidance',
    all: 'All',
    active: 'Active',
    completed: 'Completed',
    myBookings: 'My Bookings Tracker',
    noBookings: 'No bookings recorded yet',
    noBookingsSub: 'Your reservations will appear here once booked',
    switchRole: 'Switch Your Active Role',
    switchRoleSub: 'Operate as a farmer or service provider within the same app',
    selectLanguage: 'Select App Language',
    helplineTitle: 'Kisan Call Center',
    helplineNumber: '1800-180-1551 (Toll-Free 24 Hours)',
    helplineSub: 'Direct free call with Government Agricultural Scientists',
    bookingSuccess: 'Booking Successful!',
    bookingConfirmed: 'Confirm Reservation',
    totalAmount: 'Total Payable Amount',
    daysCount: 'Number of Days',
    acresCount: 'Number of Acres',
    workersCount: 'Number of Workers',
    monthsCount: 'Months',
    capacityTons: 'Capacity',
    availableTons: 'Available Space',
    searchPlaceholder: 'Search...',
    offline: 'Offline',
  },
};
